'use client'
import './globals.css'
import { useRef } from 'react';
import TaskProvider from '@/context/TaskProvider'
import { useScrollPercentage } from '@/hooks/useScrollPercentage';

/*export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const ref = useRef<HTMLBodyElement>(null);
  const { scrollPercentage } = useScrollPercentage({ ref });

  return (
    <html lang="en">
      <body ref={ ref }>
      <TaskProvider percentage={scrollPercentage}>
        {children}
      </TaskProvider>
      </body>
    </html>
  )
}
